baseurl = ""
title = "Aanand Kainth"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Aanand Kainth"
    info = "Software Engineer"
    description = "A directory of projects and blog posts I have made"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/akainth015/"
[[params.social]]
    name = "Github"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/akainth015/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 1
    url = "https://instagram.com/akainth015"
[[params.social]]
    name = "Github"
    icon = "far fa-envelope fa-2x"
    weight = 1
    url = "mailto:akainth015@gmail.com"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
